package com.lebhas.creativesaas.prompt.domain;

public enum SuggestionType {
    ENHANCEMENT,
    REWRITE,
    GENERAL_SUGGESTIONS,
    CTA_SUGGESTIONS,
    HEADLINE_SUGGESTIONS,
    OFFER_SUGGESTIONS,
    CREATIVE_ANGLE_SUGGESTIONS,
    CAMPAIGN_TONE_SUGGESTIONS,
    BUSINESS_CATEGORY_SUGGESTIONS
}
