apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  labels:
    app.kubernetes.io/name: gateway-service
    app.kubernetes.io/part-of: creative-saas
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: gateway-service
  ports:
    - name: http
      port: 80
      targetPort: http
