spring:
  application:
    name: gateway-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  config:
    import: optional:classpath:application-common.yaml

server:
  port: ${SERVER_PORT:8080}

platform:
  services:
    auth:
      base-url: ${AUTH_SERVICE_BASE_URL:http://localhost:8081}
