package com.lebhas.creativesaas.common.security;

public enum Permission {
    USER_VIEW,
    USER_CREATE,
    USER_UPDATE,
    USER_STATUS_UPDATE,
    WORKSPACE_CREATE,
    WORKSPACE_VIEW,
    WORKSPACE_UPDATE,
    WORKSPACE_STATUS_UPDATE,
    WORKSPACE_SETTINGS_VIEW,
    WORKSPACE_SETTINGS_UPDATE,
    BRAND_PROFILE_UPDATE,
    CREW_VIEW,
    CREW_INVITE,
    CREW_UPDATE,
    CREW_REMOVE,
    CREATIVE_GENERATE,
    CREATIVE_EDIT,
    CREATIVE_DOWNLOAD,
    CREATIVE_SUBMIT,
    SESSION_MANAGE
}
