FROM eclipse-temurin:21-jre

WORKDIR /app

ARG JAR_FILE
COPY ${JAR_FILE} /app/application.jar

EXPOSE 8080

ENTRYPOINT ["java", "-XX:MaxRAMPercentage=75.0", "-XX:+ExitOnOutOfMemoryError", "-jar", "/app/application.jar"]
